name: Build Electron client
on:
  push:
    branches:
      - release

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: ./build-electron-client.sh
      - uses: actions/upload-artifact@v3
        with:
          name: deb
          path: packages/electron-client/out/make/deb/x64/*.deb

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: ./build-electron-client.sh
      - uses: actions/upload-artifact@v3
        with:
          name: mac
          path: packages/electron-client/out/make/zip/darwin/x64/*.zip

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        shell: bash
        run: ./build-electron-client.sh
      - uses: actions/upload-artifact@v3
        with:
          name: win
          path: packages/electron-client/out/make/zip/win32/x64/*.zip
